/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SanBanh;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author thanh
 */
public class Frm_SanBanh extends javax.swing.JFrame {

	/**
	 * Creates new form Frm_SanBanh
	 */
	public Frm_SanBanh() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btn_Luu = new javax.swing.JButton();
                btn_Doc = new javax.swing.JButton();
                btn_Them = new javax.swing.JButton();
                btn_Xoa = new javax.swing.JButton();
                btn_Sua = new javax.swing.JButton();
                jScrollPane2 = new javax.swing.JScrollPane();
                table_Output = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                tf_MaLoaiSan = new javax.swing.JTextField();
                tf_MaSB = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                tf_MaCN = new javax.swing.JTextField();
                cbx_Sort = new javax.swing.JComboBox<>();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btn_Luu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_Luu.setText("Lưu");

                btn_Doc.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_Doc.setText("Đọc");

                btn_Them.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_Them.setText("Thêm");

                btn_Xoa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_Xoa.setText("Xoá");

                btn_Sua.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_Sua.setText("Sửa");

                table_Output.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                table_Output.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {

                        },
                        new String [] {
                                "Mã Sân Banh", "Mã Loại Sân", "Đơn Giá", "Mã Chi Nhánh"
                        }
                ) {
                        Class[] types = new Class [] {
                                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                        };
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false
                        };

                        public Class getColumnClass(int columnIndex) {
                                return types [columnIndex];
                        }

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                jScrollPane2.setViewportView(table_Output);

                jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(153, 255, 255));
                jLabel1.setText("Quản Lý Sân Banh");

                jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                jLabel2.setText("Mã Sân Banh:");

                jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                jLabel4.setText("Tiêu chí sắp xếp:");

                jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                jLabel3.setText("Mã Loại Sân:");

                tf_MaLoaiSan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

                tf_MaSB.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

                jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                jLabel5.setText("Mã Chi Nhánh:");

                tf_MaCN.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

                cbx_Sort.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                cbx_Sort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Sân Banh", "Mã Loại Sân", "Đơn Giá", "Mã Chi Nhánh" }));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(452, 452, 452)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3))
                                                                .addGap(26, 26, 26)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tf_MaSB, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tf_MaLoaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btn_Them)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn_Xoa)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn_Sua)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn_Luu)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btn_Doc))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(tf_MaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel4)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cbx_Sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(83, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(tf_MaSB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(tf_MaLoaiSan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(tf_MaCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btn_Them)
                                                        .addComponent(btn_Xoa)
                                                        .addComponent(btn_Sua)
                                                        .addComponent(btn_Luu)
                                                        .addComponent(btn_Doc)))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(cbx_Sort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frm_SanBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frm_SanBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frm_SanBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frm_SanBanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frm_SanBanh().setVisible(true);
			}
		});
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_Doc;
        private javax.swing.JButton btn_Luu;
        private javax.swing.JButton btn_Sua;
        private javax.swing.JButton btn_Them;
        private javax.swing.JButton btn_Xoa;
        private javax.swing.JComboBox<String> cbx_Sort;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTable table_Output;
        private javax.swing.JTextField tf_MaCN;
        private javax.swing.JTextField tf_MaLoaiSan;
        private javax.swing.JTextField tf_MaSB;
        // End of variables declaration//GEN-END:variables

	public JButton getBtn_Doc() {
		return btn_Doc;
	}

	public JButton getBtn_Luu() {
		return btn_Luu;
	}

	public JButton getBtn_Sua() {
		return btn_Sua;
	}

	public JButton getBtn_Them() {
		return btn_Them;
	}

	public JButton getBtn_Xoa() {
		return btn_Xoa;
	}

	public JTable getTable_Output() {
		return table_Output;
	}

	public JTextField getTf_MaCN() {
		return tf_MaCN;
	}

	public JTextField getTf_MaLoaiSan() {
		return tf_MaLoaiSan;
	}

	public JTextField getTf_MaSB() {
		return tf_MaSB;
	}

	public JComboBox<String> getCbx_Sort() {
		return cbx_Sort;
	}
	
	
}
