
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thanh
 */
public class Frm_Main extends javax.swing.JFrame {

	/**
	 * Creates new form Frm_Main
	 */
	public Frm_Main() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btn_hoaDon = new javax.swing.JButton();
                btn_SanBanh = new javax.swing.JButton();
                btn_NhanVien = new javax.swing.JButton();
                btn_KhachHang = new javax.swing.JButton();
                btn_LoaiSan = new javax.swing.JButton();
                btn_ChiNhanh = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btn_hoaDon.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_hoaDon.setText("Hoá Đơn");

                btn_SanBanh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_SanBanh.setText("Sân Banh");

                btn_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_NhanVien.setText("Nhân Viên");

                btn_KhachHang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_KhachHang.setText("Khách Hàng");

                btn_LoaiSan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_LoaiSan.setText("Loại Sân");

                btn_ChiNhanh.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
                btn_ChiNhanh.setText("Chi Nhánh");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_hoaDon)
                                        .addComponent(btn_KhachHang)
                                        .addComponent(btn_LoaiSan))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_ChiNhanh)
                                        .addComponent(btn_NhanVien)
                                        .addComponent(btn_SanBanh))
                                .addContainerGap(189, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_hoaDon)
                                        .addComponent(btn_SanBanh))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_NhanVien)
                                        .addComponent(btn_LoaiSan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_KhachHang)
                                        .addComponent(btn_ChiNhanh))
                                .addGap(133, 133, 133))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frm_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Frm_Main().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btn_ChiNhanh;
        private javax.swing.JButton btn_KhachHang;
        private javax.swing.JButton btn_LoaiSan;
        private javax.swing.JButton btn_NhanVien;
        private javax.swing.JButton btn_SanBanh;
        private javax.swing.JButton btn_hoaDon;
        // End of variables declaration//GEN-END:variables

	public JButton getBtn_LoaiSan() {
		return btn_LoaiSan;
	}

	public JButton getBtn_SanBanh() {
		return btn_SanBanh;
	}

	public JButton getBtn_hoaDon() {
		return btn_hoaDon;
	}

	public JButton getBtn_ChiNhanh() {
		return btn_ChiNhanh;
	}

	public JButton getBtn_KhachHang() {
		return btn_KhachHang;
	}

	public JButton getBtn_NhanVien() {
		return btn_NhanVien;
	}
}
